
<!-- 
<h2 class="home-title">enregistrez vous</h2>
<div class="separateur-title"></div>	
<div class="row">
	*/<?php ?>*/
</div> -->

<div id="container">
	<?php  require('apps/chat_message.php') ?>
	<?php require('apps/chat.php') ?>
		

<div class="row last-member">	
	<h2 class="home-title">Derniers membres inscrits</h2>
	<div class="separateur-title"></div>	
	<?php require('apps/home_last_member.php'); ?>

</div>
