<div class="mpContent">
	<div class='row'>
		<div class="col-md-1 col-xs-1">
			<div class="autheurCom">
				<img src="<?=$mp['avatar'] ?>" alt="tg" width="100%">
				<p>
					<a href="?page=profil&id=<?php echo $mp['id_writer'] ?>"><?php echo $mp['login'] ?></a>
				</p>
			</div>
		</div>
		<div class="col-md-11 col-xs-11">
			<p class="mp">
				<?php echo nl2br( $mp['content'] );?>
			</p>
		</div>
	</div>
		<button type="button" class="btn btn-primary js_answer" data-mp="<?=$mp['pmid']?>">Répondre</button>
	</p>
</div>


