<div class="mpContent">
	<div class='row'>
		<div class="col-md-1 col-xs-1">
			<div class="autheurCom">
				<img src="<?=$mp['avatar'] ?>" alt="tg" width="100%">
				<p>
					<a href="?page=profil&id=<?php echo $mp['id_writer'] ?>"><?php echo $mp['login'] ?></a>
				</p>
			</div>
		</div>
		<div class="col-md-11 col-xs-11">
			<p class="mp">
				<?php echo nl2br( $mp['content'] );?>
			</p>
		</div>
	</div>
		<button type="button" class="btn btn-primary js_answer" data-mp="<?=$mp['pmid']?>">Répondre</button>
	</p>
</div>


<form method="POST" action="index.php?page=addMp">
	<!-- <label><input class="form-control" type="text" name="loginTarget" value="<?=htmlentities($loginTarget)?>" placeholder="login du membre"></label> -->

	<textarea class="form-control" rows="3"
	type="text" name="content" value="<?=htmlentities($content)?>">
	</textarea>
	<br/>
	<input class="btn btn-primary" type="submit" value="Valider">

	
		
</form>

