
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="?page=home">chat</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="?page=home">Home <span class="sr-only">(current)</span></a></li>
        
      </ul>

    <ul class="nav navbar-nav navbar-right">
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">MP (<?=$unread?>)</a>
          <ul class="dropdown-menu">
          <li><a href="?page=mp">Liste MP (<?=$unread?>)</a></li>
          <li><a href="?page=addMp">Envoyer MP</a></li>
    </ul>
    </li>

        <li><a href="?page=userlist">User list</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="login"><?php echo $_SESSION['login']; ?> <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <a href="?page=profil&id=<?=$_SESSION['id']?>" class="lien-profil">Voir mon profil</a> 
          <?php require('apps/logout.php'); ?>
        <li role="separator" class="divider"></li>
            <li class="register"><a href="?page=register">Register</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>