<div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
    	<div class="panel panel-default">
    		<div class="panel-heading">
		    		<h3 class="panel-title">Enregistrez votre compte</h3>
		 			</div>
		 			<div class="panel-body">
		    		<form role="form" method="post">
		    			<div style="background-color:red;"><?=implode('<br/>', $errors)?></div>
    					<div class="row">
    			
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">

		                <input type="text" name="nom" id="nom" class="form-control input-sm" value='<?=htmlentities($nom)?>' placeholder="Nom">

		    					</div>
		    				</div>
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="text" name="prenom" id="prenom" class="form-control input-sm" value='<?=htmlentities($prenom)?>' placeholder="Prénom">
		    					</div>
		    				</div>
		    			</div>


		    			<div class="form-group">
    						<input type="text" name="login" id="login" class="form-control input-sm" placeholder="Pseudo" value="<?=htmlentities($login)?>">
    					</div>

		    			<div class="form-group">
		    				<input type="email" name="email" id="email" class="form-control input-sm" value='<?=htmlentities($email)?>' placeholder="Email">
		    			</div>

		    			<div class="row">
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="password" name="password" id="password" class="form-control input-sm" value='<?=htmlentities($password)?>' placeholder="Mot de passe">
		    					</div>
		    				</div>
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="password" name="password2" id="password_confirmation" class="form-control input-sm" value='<?=htmlentities($password2)?>' placeholder="Confirmez mot de passe">
		    					</div>
		    				</div>
		    			</div>
		    			
		    			<input type="submit" value="Enregistrer" class="btn btn-info btn-block">
		    		
		    		</form>
		    	
		    	</div>
    		</div>
		</div>
	</div>