<form action="index.php?page=statut" method="post">

<select class="form-control" name='statut' id='statut'>
  <option value="0" <?php if($user['rights']==0){echo 'selected';}?>>Banni</option>
  <option value="1" <?php if($user['rights']==1){echo 'selected';}?>>Utilisateur</option>
  <option value="2" <?php if($user['rights']==2){echo 'selected';}?>>Admin</option>
</select>
<input type="hidden" value="<?=$user['id']?>" name="id">
<button type="submit" class="btn btn-warning validation">valider modification</button>

</form>